### ISSUE TITLE
Hey I would like to add a remove item button can you assign me this topic?Is this there for hacktoberfest 2021?

### ISSUE THREAD

**Issue by Gaurangseven** [code-knackerin/ShoppingList#15]

**Comment by code-knackerin** [comment]
Hey, yes you can add this remove button :) It was my plan for the future. :D happy hacking

**Comment by Gaurangseven** [comment]
Hey can you add the Hacktoberfest tag to this task.

**Comment by code-knackerin** [comment]
The Repo ShoppingList has the #hacktoberfest tag :)
